#!/bin/bash
conda install -c conda-forge nodejs
jupyter labextension install @jupyter-widgets/jupyterlab-manager 
jupyter labextension install @jupyter-voila/jupyterlab-preview
jupyter labextension install  nglview-js-widgets
jupyter labextension install jupyter-threejs
jupyter labextension install jupyter-matplotlib
jupyter nbextension      enable --py --sys-prefix appmode
jupyter serverextension  enable --py --sys-prefix appmode
jupyter nbextension      enable --py widgetsnbextension
jupyter nbextension install --py --symlink --sys-prefix nglview
jupyter nbextension enable --py --sys-prefix nglview
jupyter lab build 
git clone https://github.com/osscar-org/reprint-magic.git
cd reprint-magic
pip install -e .
cd ..
git clone git@github.com:Zulko/vapory.git
cd vapory 
pip install -e . 
