# environment.yml
name: osscar_docs
channels:
  - conda-forge
dependencies:
- python=3.8
- nodejs
- numpy
- sphinx
- nbsphinx
- jupyter_sphinx
- nglview 
- ase 
- pip
- pip:
    - widget-periodictable 
